version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "seano"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6g7zok6515dn"
s3_prefix = "seano"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
